config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "articles#index"

  resources :users do
    resources :articles
  end

  resources :articles do
    resources :comments
  end

  resource :relationships, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  include Visible

  # To destroy the comments when the article is deleted"
  has_many :comments, dependent: :destroy

  # Title must contain at least one non-whitespace character
  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }

  # Articles associated to the User with "article_id" on users table.
  belongs_to :user, optional: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible

  # Sets up an Active Record association (each comment belongs to an article)
  belongs_to :article
  belongs_to :user
end

app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = ['public', 'private', 'archived']

  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end

  class_methods do
    def public_count
      where(status: 'public').count
    end
  end

  def archived?
    status == 'archived'
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :articles, dependent: :destroy
  has_many :comments

  has_many :active_relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :passive_relationships, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy

  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  def follow(user)
    active_relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    active_relationships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    following.include?(user)
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    #To add the new input field in the registration form
    devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name])
  end

  def after_sign_up_path_for(resource)
    if resource.is_a?(User)
      current_user
    else
      super
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
    @users = User.all
  end

  def show
    @user = User.find_by(params[:article_id])
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id
    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to root_path, status: :see_other
  end

  private

  def article_params
    # The create action can access with params[:article][:title]
    params.require(:article).permit(:title, :body, :status, :user_id)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def new
    @comment = Comment.new
  end

  def create
   @article = Article.find(params[:article_id])
   @comment = Comment.new(comment_params.merge(user_id: current_user.id, article_id: @article.id))
    if @comment.save
      redirect_to article_path(@article)
    else
      redirect_to user_path(current_user)
    end
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article), status: 303
  end

  private

    def comment_params
      params.require(:comment).permit(:body, :status)
    end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  before_action :authenticate_user!
  before_action :find_user # To define user first before executing the other methods.

  def create
    current_user.follow(@user)
    redirect_to @user
  end

  def destroy
    current_user.unfollow(@user)
    redirect_to @user
  end

  def find_user
    @user = User.find(params[:user_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @articles = @user.articles
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :user_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<div class='container'>
  <%= form_with model: article do |form| %>
    <div class='container'>
      <%= form.label :title, class: 'form-label h5 mb-0' %><br>
      <%= form.text_field :title, class: 'form-control'%>
      <% article.errors.full_messages_for(:title).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div class='container'>
      <%= form.label :body, class: 'form-label h5 mb-0' %><br>
      <%= form.text_area :body, class:'form-control' %><br>
      <% article.errors.full_messages_for(:body).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div class='d-flex justify-content-center gap-4 align-items-center'>
      <%= form.submit class: 'btn btn-secondary' %>
      <div class='d-flex gap-1'>
        <%= form.label :status %><br>
        <%= form.select :status, ['public', 'private', 'archived'], selected: 'public', class: 'form-select' %>
      <div>
    </div>
  <% end %>
<div>

app/views/articles/_navbar.html.erb
<nav class='navbar navbar-expand-lg bg-secondary'>
  <div class='container-fluid '>

      <ul class='navbar-nav me-auto mb-2 mb-lg-0'>
        <li class='nav-item'>
          <a class='nav-link active text-white link-navbar' aria-current='page' href='/'>Home</a>
        </li>
      </ul>

      <ul class='nav navbar-nav navbar-right'>
        <% if user_signed_in? %>
          <div class='d-flex gap-3'>
            <li><%= link_to current_user.user_name, user_path(current_user) %></li>
            <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
          </div>
        <% else %>
          <li class='nav-item'>
            <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link active text-white link-navbar' %>
          </li>
          <li class='nav-item'>
            <%= link_to 'Login', new_user_session_path, class: 'nav-link active text-white link-navbar' %>
          </li>
          <% end %>
      </ul>

  </div>
</nav>

app/views/articles/edit.html.erb
<%= render 'navbar' %>

<h1 class='text-center mt-3'>Edit Article</h1>

<%= render 'form', article: @article %>

app/views/articles/index.html.erb
<%= render 'navbar' %>

<div class='container w-75'>
  <h1 class='text-center mt-3'>Articles</h1>

  Our blog has <%= Article.public_count %> articles and counting!

  <ul class='list-group'>
    <% @articles.each do |article| %>
      <% unless article.archived? %>
        <li class='list-group-item d-flex justify-content-between align-items-center'>
          <p class='mb-0'><%= link_to article.title, article, class: 'text-dark li-articles' %></p>
          <% if user_signed_in? %>
            <p class='mb-0'><%= link_to article.user.user_name, user_path(article.user_id), class: 'text-dark li-articles' %></p>
          <% end %>
        </li>
      <% end %>
    <% end %>
  </ul>

  <% if user_signed_in? %>
    <div class='d-flex justify-content-center'>
      <%= link_to 'New Article', new_article_path, class: 'btn btn-secondary mt-3' %>
    </div>
  <% else %>
    <div class='d-flex justify-content-center'>
      <%= link_to 'New Article', new_user_registration_path, class: 'btn btn-secondary mt-3' %>
    </div>
  <% end %>

  <% if user_signed_in? %>
    <h1 class='text-center mt-3'>Users</h1>

    <ul class='list-group my-3 w-50 mx-auto'>
      <% @users.each do |user| %>
        <li class='list-group-item d-flex justify-content-center align-items-center'>
          <p class='mb-0'><%= link_to user.user_name, user_path(user.id), class: 'text-dark li-articles' %></p>
        </li>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/articles/new.html.erb
<%= render 'navbar' %>

<h1 class='text-center mt-3'>New Article</h1>

<%= render 'form', article: @article %>

app/views/articles/show.html.erb
<%= render 'navbar' %>

<div class='container'>
  <h1 class='text-center mt-3'><%= @article.title %></h1>

  <p><%= @article.body %></p>

  <ul class='d-flex justify-content-center gap-3'>
     <% if user_signed_in? %>
      <% if current_user.id == @article.user.id %>
        <div class='btn btn-outline-primary'>
          <li><%= link_to 'Edit', edit_article_path(@article), class: 'text-dark'  %></li>
        </div>
        <div class='btn btn-outline-danger'>
        <li><%= link_to 'Destroy', article_path(@article), data: {
                          turbo_method: :delete,
                          turbo_confirm: 'Are you sure?'
                        }, class: 'text-dark' %>
        </li>
        </div>
      <% end %>
    <% end %>
  </ul>
  <% if @article.comments.any? %>
    <h2>Comments</h2>
    <%= render @article.comments %>
  <% end %>
  <%puts current_user.user_name%>
  <%puts @user.user_name%>

  <% if current_user.following?(@user) %>
    <%= render 'comments/form' %>
  <% end %>
</div>

app/views/comments/_comment.html.erb
<div class='card my-3'>
  <div class="card-body">
    <% unless comment.archived? %>
      <p>
        <strong>Commenter:</strong>
        <% author = User.find(comment.user_id) %>
        <%= author.user_name %>
      </p>

      <p>
        <strong>Comment:</strong>
        <%= comment.body %>
      </p>

      <% if user_signed_in? and comment.user_id == current_user.id %>
        <div class='btn btn-outline-danger mb-3'>
          <%= link_to 'Delete Comment', [comment.article, comment], data: {
                        turbo_method: :delete,
                        turbo_confirm: 'Are you sure?'
                      } %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/comments/_form.html.erb
<div class='container'>
  <%= form_with model: [ @article, @article.comments.build ] do |form| %>
    <p>
      <%= form.label :body, 'Comment', class: 'text-primary fw-bold fs-3' %><br>
      <%= form.text_area :body, class: 'form-control' %>
    </p>

    <% if user_signed_in? %>
      <div class='d-flex justify-content-center gap-4 align-items-center'>
        <%= form.submit class: 'btn btn-secondary' %>
        <div class='d-flex gap-1'>
          <%= form.label :status %><br>
          <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
        </div>
      </div>
    <% else %>
      <div class='d-flex justify-content-center'>
        <%= link_to 'Create Comment', new_user_registration_path, class: 'btn btn-secondary mt-3' %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Articles Blog</title>
    <meta name='viewport' content='width=device-width,initial-scale=1'>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', 'data-turbo-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
      <%= yield %>

    <div class='mt-3' >
      <% if notice %><div class='alert alert-success'> <%= notice %> </div><% end %>
      <% if alert %><div class='alert alert-warning'> <%= alert %> </div><% end %>
    </div>
  </body>
</html>

app/views/users/show.html.erb
<%= render 'articles/navbar' %>

<div class='container'>
  <h2 class='text-center mt-3'>Profile</h2>

  <h3 class='text-center mt-3'><%= @user.user_name %></h3>

  <div class='container d-flex justify-content-center gap-3'>
    <% if user_signed_in? and !current_page?(current_user) %>
      <% if current_user.following?(@user) %>
          <%= button_to 'Unfollow', relationships_path(user_id: @user.id), method: :delete, class: 'btn btn-outline-primary' %>
      <% else %>
        <%= button_to 'Follow', relationships_path(user_id: @user.id), class: 'btn btn-outline-primary' %>
      <% end %>
    <% end %>
  </div>

  <% if user_signed_in? and Article.any? %>
    <% @articles.each do |article| %>
      <div class='card my-3'>
        <div class="card-body">
          <h5 class="card-title"><%= article.title %></h5>
          <p class="card-text"><%= article.body %></p>
        </div>
      </div>
      <% if current_user.id == article.user.id %>
        <ul class='d-flex justify-content-center gap-3'>
          <div class='btn btn-outline-primary'>
            <li><%= link_to 'Edit', edit_article_path(article), class: 'text-dark'  %></li>
          </div>

          <div class='btn btn-outline-danger'>
            <li><%= link_to 'Destroy', article_path(article), data: {
                                turbo_method: :delete,
                                turbo_confirm: 'Are you sure?'
                              }, class: 'text-dark' %>
            </li>
          </div>
        </ul>
      <% end %>

      <% if article.comments.any? %>
        <h2>Comments</h2>
          <%= render article.comments %>
      <% end %>

      <% if current_user.following?(@user) %>
        <% @article = article %>
        <%= render 'comments/form' %>
      <% end %>
    <% end %>
  <% end %>
</div>

<% if current_user.id == @user.id %>
  <div class='d-flex justify-content-center'>
    <%= link_to 'New Article', new_article_path, class: 'btn btn-secondary mt-3' %>
  </div>
<% end %>